-- Run this in the Supabase SQL editor (Project → SQL Editor → New query).

create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  age int,
  email text
);

create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  task_name text not null,
  is_completed boolean default false,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;

create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can manage own tasks" on public.tasks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
